name: terraform-ci
on: [push, pull_request]
jobs:
  tf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
      - run: cd iac && terraform fmt -check
      - run: cd iac && terraform init -backend=false
      - run: cd iac && terraform validate
